version: "3.9"

services:
  web:
    build: .
    container_name: inventory_sys_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_sys_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - web
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
